# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SolMOKE_GUI.ui'
#
# Created: Mon Jul 25 09:12:36 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1122, 786)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1122, 786))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1122, 760))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabMotionCtrlWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMotionCtrlWidget.sizePolicy().hasHeightForWidth())
        self.tabMotionCtrlWidget.setSizePolicy(sizePolicy)
        self.tabMotionCtrlWidget.setMaximumSize(QtCore.QSize(1104, 742))
        self.tabMotionCtrlWidget.setObjectName(_fromUtf8("tabMotionCtrlWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(90, 10, 181, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridFrame_5 = QtGui.QFrame(self.tab)
        self.gridFrame_5.setGeometry(QtCore.QRect(40, 90, 291, 171))
        self.gridFrame_5.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_5.setObjectName(_fromUtf8("gridFrame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridFrame_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.readTempSetup = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readTempSetup.setFont(font)
        self.readTempSetup.setAutoFillBackground(True)
        self.readTempSetup.setText(_fromUtf8(""))
        self.readTempSetup.setObjectName(_fromUtf8("readTempSetup"))
        self.gridLayout_5.addWidget(self.readTempSetup, 5, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.setTempSetup = QtGui.QLineEdit(self.gridFrame_5)
        self.setTempSetup.setObjectName(_fromUtf8("setTempSetup"))
        self.gridLayout_5.addWidget(self.setTempSetup, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 5, 0, 1, 1)
        self.heaterOutBarSetup = QtGui.QProgressBar(self.gridFrame_5)
        self.heaterOutBarSetup.setProperty("value", 0)
        self.heaterOutBarSetup.setOrientation(QtCore.Qt.Horizontal)
        self.heaterOutBarSetup.setObjectName(_fromUtf8("heaterOutBarSetup"))
        self.gridLayout_5.addWidget(self.heaterOutBarSetup, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)
        self.setTempRampSetup = QtGui.QLineEdit(self.gridFrame_5)
        self.setTempRampSetup.setObjectName(_fromUtf8("setTempRampSetup"))
        self.gridLayout_5.addWidget(self.setTempRampSetup, 3, 1, 1, 1)
        self.connectLakeshoreBtn = QtGui.QPushButton(self.tab)
        self.connectLakeshoreBtn.setGeometry(QtCore.QRect(40, 50, 171, 31))
        self.connectLakeshoreBtn.setObjectName(_fromUtf8("connectLakeshoreBtn"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(660, 10, 131, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_45 = QtGui.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(120, 340, 131, 31))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridFrame_11 = QtGui.QFrame(self.tab)
        self.gridFrame_11.setGeometry(QtCore.QRect(40, 420, 301, 201))
        self.gridFrame_11.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_11.setObjectName(_fromUtf8("gridFrame_11"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gridFrame_11)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_41 = QtGui.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_16.addWidget(self.label_41, 4, 0, 1, 1)
        self.setMotPosSetup = QtGui.QLineEdit(self.gridFrame_11)
        self.setMotPosSetup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setMotPosSetup.setObjectName(_fromUtf8("setMotPosSetup"))
        self.gridLayout_16.addWidget(self.setMotPosSetup, 0, 1, 1, 1)
        self.readMotPosSetup = QtGui.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readMotPosSetup.setFont(font)
        self.readMotPosSetup.setAutoFillBackground(True)
        self.readMotPosSetup.setText(_fromUtf8(""))
        self.readMotPosSetup.setObjectName(_fromUtf8("readMotPosSetup"))
        self.gridLayout_16.addWidget(self.readMotPosSetup, 4, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_16.addWidget(self.label_46, 1, 0, 1, 1)
        self.setMotVelocitySetup = QtGui.QLineEdit(self.gridFrame_11)
        self.setMotVelocitySetup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setMotVelocitySetup.setObjectName(_fromUtf8("setMotVelocitySetup"))
        self.gridLayout_16.addWidget(self.setMotVelocitySetup, 1, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_16.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_16.addWidget(self.label_47, 2, 0, 1, 1)
        self.setMotAccSetup = QtGui.QLineEdit(self.gridFrame_11)
        self.setMotAccSetup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setMotAccSetup.setObjectName(_fromUtf8("setMotAccSetup"))
        self.gridLayout_16.addWidget(self.setMotAccSetup, 2, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setText(_fromUtf8("SetDeceleration"))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_16.addWidget(self.label_49, 3, 0, 1, 1)
        self.setMotDecSetup = QtGui.QLineEdit(self.gridFrame_11)
        self.setMotDecSetup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setMotDecSetup.setText(_fromUtf8(""))
        self.setMotDecSetup.setObjectName(_fromUtf8("setMotDecSetup"))
        self.gridLayout_16.addWidget(self.setMotDecSetup, 3, 1, 1, 1)
        self.stopMotSetup = QtGui.QPushButton(self.gridFrame_11)
        self.stopMotSetup.setObjectName(_fromUtf8("stopMotSetup"))
        self.gridLayout_16.addWidget(self.stopMotSetup, 5, 0, 1, 1)
        self.resetMotSetup = QtGui.QPushButton(self.gridFrame_11)
        self.resetMotSetup.setObjectName(_fromUtf8("resetMotSetup"))
        self.gridLayout_16.addWidget(self.resetMotSetup, 5, 1, 1, 1)
        self.connectGMWBtn = QtGui.QPushButton(self.tab)
        self.connectGMWBtn.setGeometry(QtCore.QRect(380, 50, 171, 31))
        self.connectGMWBtn.setObjectName(_fromUtf8("connectGMWBtn"))
        self.connectMotorBtn = QtGui.QPushButton(self.tab)
        self.connectMotorBtn.setGeometry(QtCore.QRect(40, 380, 171, 31))
        self.connectMotorBtn.setObjectName(_fromUtf8("connectMotorBtn"))
        self.gridFrame_2 = QtGui.QFrame(self.tab)
        self.gridFrame_2.setGeometry(QtCore.QRect(380, 90, 311, 171))
        self.gridFrame_2.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_2.setObjectName(_fromUtf8("gridFrame_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridFrame_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.readFieldGMWSetup = QtGui.QLabel(self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readFieldGMWSetup.setFont(font)
        self.readFieldGMWSetup.setAutoFillBackground(True)
        self.readFieldGMWSetup.setText(_fromUtf8(""))
        self.readFieldGMWSetup.setObjectName(_fromUtf8("readFieldGMWSetup"))
        self.gridLayout_9.addWidget(self.readFieldGMWSetup, 3, 1, 1, 1)
        self.poleTypeGMWSetup = QtGui.QComboBox(self.gridFrame_2)
        self.poleTypeGMWSetup.setAccessibleName(_fromUtf8(""))
        self.poleTypeGMWSetup.setEditable(False)
        self.poleTypeGMWSetup.setMaxVisibleItems(2)
        self.poleTypeGMWSetup.setObjectName(_fromUtf8("poleTypeGMWSetup"))
        self.gridLayout_9.addWidget(self.poleTypeGMWSetup, 0, 0, 1, 1)
        self.setFieldGMWSetup = QtGui.QLineEdit(self.gridFrame_2)
        self.setFieldGMWSetup.setObjectName(_fromUtf8("setFieldGMWSetup"))
        self.gridLayout_9.addWidget(self.setFieldGMWSetup, 2, 1, 1, 1)
        self.gapValueGMWSetup = QtGui.QComboBox(self.gridFrame_2)
        self.gapValueGMWSetup.setObjectName(_fromUtf8("gapValueGMWSetup"))
        self.gridLayout_9.addWidget(self.gapValueGMWSetup, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridFrame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_9.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridFrame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_9.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridFrame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 1, 0, 1, 1)
        self.setMaxCurrentGMW = QtGui.QLineEdit(self.gridFrame_2)
        self.setMaxCurrentGMW.setObjectName(_fromUtf8("setMaxCurrentGMW"))
        self.gridLayout_9.addWidget(self.setMaxCurrentGMW, 1, 1, 1, 1)
        self.gridFrame_7 = QtGui.QFrame(self.tab)
        self.gridFrame_7.setGeometry(QtCore.QRect(740, 90, 311, 171))
        self.gridFrame_7.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_7.setObjectName(_fromUtf8("gridFrame_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gridFrame_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.readFieldCAYLARSetup = QtGui.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readFieldCAYLARSetup.setFont(font)
        self.readFieldCAYLARSetup.setAutoFillBackground(True)
        self.readFieldCAYLARSetup.setText(_fromUtf8(""))
        self.readFieldCAYLARSetup.setObjectName(_fromUtf8("readFieldCAYLARSetup"))
        self.gridLayout_10.addWidget(self.readFieldCAYLARSetup, 3, 1, 1, 1)
        self.setFieldRampCAYLARSetup = QtGui.QLineEdit(self.gridFrame_7)
        self.setFieldRampCAYLARSetup.setText(_fromUtf8(""))
        self.setFieldRampCAYLARSetup.setObjectName(_fromUtf8("setFieldRampCAYLARSetup"))
        self.gridLayout_10.addWidget(self.setFieldRampCAYLARSetup, 2, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_10.addWidget(self.label_20, 3, 0, 1, 1)
        self.setFieldCAYLARSetup = QtGui.QLineEdit(self.gridFrame_7)
        self.setFieldCAYLARSetup.setObjectName(_fromUtf8("setFieldCAYLARSetup"))
        self.gridLayout_10.addWidget(self.setFieldCAYLARSetup, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_10.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_10.addWidget(self.label_21, 1, 0, 1, 1)
        self.gapValueCAYLARSetup = QtGui.QComboBox(self.gridFrame_7)
        self.gapValueCAYLARSetup.setObjectName(_fromUtf8("gapValueCAYLARSetup"))
        self.gridLayout_10.addWidget(self.gapValueCAYLARSetup, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_10.addWidget(self.label_27, 0, 0, 1, 1)
        self.connectCAYLARBtn = QtGui.QPushButton(self.tab)
        self.connectCAYLARBtn.setGeometry(QtCore.QRect(740, 50, 171, 31))
        self.connectCAYLARBtn.setObjectName(_fromUtf8("connectCAYLARBtn"))
        self.ledLakeshore = QtGui.QLabel(self.tab)
        self.ledLakeshore.setEnabled(False)
        self.ledLakeshore.setGeometry(QtCore.QRect(280, 50, 31, 31))
        self.ledLakeshore.setAutoFillBackground(False)
        self.ledLakeshore.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledLakeshore.setMidLineWidth(0)
        self.ledLakeshore.setText(_fromUtf8(""))
        self.ledLakeshore.setPixmap(QtGui.QPixmap(_fromUtf8("IMAGES/ledOFF_patrat.png")))
        self.ledLakeshore.setScaledContents(True)
        self.ledLakeshore.setMargin(0)
        self.ledLakeshore.setObjectName(_fromUtf8("ledLakeshore"))
        self.ledGMW = QtGui.QLabel(self.tab)
        self.ledGMW.setEnabled(False)
        self.ledGMW.setGeometry(QtCore.QRect(640, 50, 31, 31))
        self.ledGMW.setAutoFillBackground(False)
        self.ledGMW.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledGMW.setMidLineWidth(0)
        self.ledGMW.setText(_fromUtf8(""))
        self.ledGMW.setPixmap(QtGui.QPixmap(_fromUtf8("IMAGES/ledOFF_patrat.png")))
        self.ledGMW.setScaledContents(True)
        self.ledGMW.setMargin(0)
        self.ledGMW.setObjectName(_fromUtf8("ledGMW"))
        self.ledCAYLAR = QtGui.QLabel(self.tab)
        self.ledCAYLAR.setEnabled(False)
        self.ledCAYLAR.setGeometry(QtCore.QRect(1000, 50, 31, 31))
        self.ledCAYLAR.setAutoFillBackground(False)
        self.ledCAYLAR.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledCAYLAR.setMidLineWidth(0)
        self.ledCAYLAR.setText(_fromUtf8(""))
        self.ledCAYLAR.setPixmap(QtGui.QPixmap(_fromUtf8("IMAGES/ledOFF_patrat.png")))
        self.ledCAYLAR.setScaledContents(True)
        self.ledCAYLAR.setMargin(0)
        self.ledCAYLAR.setObjectName(_fromUtf8("ledCAYLAR"))
        self.ledMotor = QtGui.QLabel(self.tab)
        self.ledMotor.setEnabled(False)
        self.ledMotor.setGeometry(QtCore.QRect(290, 380, 31, 31))
        self.ledMotor.setAutoFillBackground(False)
        self.ledMotor.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledMotor.setMidLineWidth(0)
        self.ledMotor.setText(_fromUtf8(""))
        self.ledMotor.setPixmap(QtGui.QPixmap(_fromUtf8("IMAGES/ledOFF_patrat.png")))
        self.ledMotor.setScaledContents(True)
        self.ledMotor.setMargin(0)
        self.ledMotor.setObjectName(_fromUtf8("ledMotor"))
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(650, 340, 131, 31))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.ledSRS = QtGui.QLabel(self.tab)
        self.ledSRS.setEnabled(False)
        self.ledSRS.setGeometry(QtCore.QRect(650, 380, 31, 31))
        self.ledSRS.setAutoFillBackground(False)
        self.ledSRS.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledSRS.setMidLineWidth(0)
        self.ledSRS.setText(_fromUtf8(""))
        self.ledSRS.setPixmap(QtGui.QPixmap(_fromUtf8("IMAGES/ledOFF_patrat.png")))
        self.ledSRS.setScaledContents(True)
        self.ledSRS.setMargin(0)
        self.ledSRS.setObjectName(_fromUtf8("ledSRS"))
        self.connectSRSBtn = QtGui.QPushButton(self.tab)
        self.connectSRSBtn.setGeometry(QtCore.QRect(380, 380, 171, 31))
        self.connectSRSBtn.setObjectName(_fromUtf8("connectSRSBtn"))
        self.ledPrinceton = QtGui.QLabel(self.tab)
        self.ledPrinceton.setEnabled(False)
        self.ledPrinceton.setGeometry(QtCore.QRect(1000, 380, 31, 31))
        self.ledPrinceton.setAutoFillBackground(False)
        self.ledPrinceton.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledPrinceton.setMidLineWidth(0)
        self.ledPrinceton.setText(_fromUtf8(""))
        self.ledPrinceton.setPixmap(QtGui.QPixmap(_fromUtf8("IMAGES/ledOFF_patrat.png")))
        self.ledPrinceton.setScaledContents(True)
        self.ledPrinceton.setMargin(0)
        self.ledPrinceton.setObjectName(_fromUtf8("ledPrinceton"))
        self.connectPrincetonBtn = QtGui.QPushButton(self.tab)
        self.connectPrincetonBtn.setGeometry(QtCore.QRect(740, 380, 221, 31))
        self.connectPrincetonBtn.setObjectName(_fromUtf8("connectPrincetonBtn"))
        self.gridFrame_9 = QtGui.QFrame(self.tab)
        self.gridFrame_9.setGeometry(QtCore.QRect(740, 420, 311, 181))
        self.gridFrame_9.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_9.setObjectName(_fromUtf8("gridFrame_9"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gridFrame_9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.readPrincexSetup = QtGui.QLabel(self.gridFrame_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readPrincexSetup.setFont(font)
        self.readPrincexSetup.setAutoFillBackground(True)
        self.readPrincexSetup.setText(_fromUtf8(""))
        self.readPrincexSetup.setObjectName(_fromUtf8("readPrincexSetup"))
        self.gridLayout_12.addWidget(self.readPrincexSetup, 2, 1, 1, 1)
        self.readPrinceySetup = QtGui.QLabel(self.gridFrame_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readPrinceySetup.setFont(font)
        self.readPrinceySetup.setAutoFillBackground(True)
        self.readPrinceySetup.setText(_fromUtf8(""))
        self.readPrinceySetup.setObjectName(_fromUtf8("readPrinceySetup"))
        self.gridLayout_12.addWidget(self.readPrinceySetup, 3, 1, 1, 1)
        self.autoMeasPrince = QtGui.QPushButton(self.gridFrame_9)
        self.autoMeasPrince.setObjectName(_fromUtf8("autoMeasPrince"))
        self.gridLayout_12.addWidget(self.autoMeasPrince, 0, 0, 1, 1)
        self.autoOffsetPrince = QtGui.QPushButton(self.gridFrame_9)
        self.autoOffsetPrince.setObjectName(_fromUtf8("autoOffsetPrince"))
        self.gridLayout_12.addWidget(self.autoOffsetPrince, 0, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridFrame_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_12.addWidget(self.label_38, 3, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridFrame_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_12.addWidget(self.label_36, 2, 0, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 420, 311, 221))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.autoOffsetSRS = QtGui.QPushButton(self.verticalLayoutWidget)
        self.autoOffsetSRS.setObjectName(_fromUtf8("autoOffsetSRS"))
        self.gridLayout_13.addWidget(self.autoOffsetSRS, 0, 1, 1, 1)
        self.autoMeasSRS = QtGui.QPushButton(self.verticalLayoutWidget)
        self.autoMeasSRS.setObjectName(_fromUtf8("autoMeasSRS"))
        self.gridLayout_13.addWidget(self.autoMeasSRS, 0, 0, 1, 1)
        self.resetSRS = QtGui.QPushButton(self.verticalLayoutWidget)
        self.resetSRS.setObjectName(_fromUtf8("resetSRS"))
        self.gridLayout_13.addWidget(self.resetSRS, 1, 0, 1, 1)
        self.autoSensSRS = QtGui.QPushButton(self.verticalLayoutWidget)
        self.autoSensSRS.setObjectName(_fromUtf8("autoSensSRS"))
        self.gridLayout_13.addWidget(self.autoSensSRS, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_13)
        self.gridFrame_8 = QtGui.QFrame(self.verticalLayoutWidget)
        self.gridFrame_8.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_8.setObjectName(_fromUtf8("gridFrame_8"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gridFrame_8)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_35 = QtGui.QLabel(self.gridFrame_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_11.addWidget(self.label_35, 2, 0, 1, 1)
        self.readSRSxSetup = QtGui.QLabel(self.gridFrame_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Constantia"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readSRSxSetup.setFont(font)
        self.readSRSxSetup.setAutoFillBackground(True)
        self.readSRSxSetup.setText(_fromUtf8(""))
        self.readSRSxSetup.setObjectName(_fromUtf8("readSRSxSetup"))
        self.gridLayout_11.addWidget(self.readSRSxSetup, 2, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.gridFrame_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_11.addWidget(self.label_37, 3, 0, 1, 1)
        self.readSRSySetup = QtGui.QLabel(self.gridFrame_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readSRSySetup.setFont(font)
        self.readSRSySetup.setAutoFillBackground(True)
        self.readSRSySetup.setText(_fromUtf8(""))
        self.readSRSySetup.setObjectName(_fromUtf8("readSRSySetup"))
        self.gridLayout_11.addWidget(self.readSRSySetup, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.gridFrame_8)
        self.tabMotionCtrlWidget.addTab(self.tab, _fromUtf8(""))
        self.tabTimescan = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabTimescan.sizePolicy().hasHeightForWidth())
        self.tabTimescan.setSizePolicy(sizePolicy)
        self.tabTimescan.setMaximumSize(QtCore.QSize(1100, 705))
        self.tabTimescan.setMouseTracking(False)
        self.tabTimescan.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabTimescan.setAcceptDrops(False)
        self.tabTimescan.setAccessibleName(_fromUtf8(""))
        self.tabTimescan.setAccessibleDescription(_fromUtf8(""))
        self.tabTimescan.setAutoFillBackground(False)
        self.tabTimescan.setObjectName(_fromUtf8("tabTimescan"))
        self.gridFrame = QtGui.QFrame(self.tabTimescan)
        self.gridFrame.setGeometry(QtCore.QRect(4, 457, 241, 231))
        self.gridFrame.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.gridLayout = QtGui.QGridLayout(self.gridFrame)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stopTimescan = QtGui.QPushButton(self.gridFrame)
        self.stopTimescan.setObjectName(_fromUtf8("stopTimescan"))
        self.gridLayout.addWidget(self.stopTimescan, 7, 0, 1, 1)
        self.startTimescan = QtGui.QPushButton(self.gridFrame)
        self.startTimescan.setObjectName(_fromUtf8("startTimescan"))
        self.gridLayout.addWidget(self.startTimescan, 5, 0, 1, 1)
        self.saveTimescanFileName = QtGui.QLineEdit(self.gridFrame)
        self.saveTimescanFileName.setText(_fromUtf8(""))
        self.saveTimescanFileName.setObjectName(_fromUtf8("saveTimescanFileName"))
        self.gridLayout.addWidget(self.saveTimescanFileName, 2, 0, 1, 1)
        self.workDirControl = QtGui.QPushButton(self.gridFrame)
        self.workDirControl.setObjectName(_fromUtf8("workDirControl"))
        self.gridLayout.addWidget(self.workDirControl, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tempRadioBtn = QtGui.QRadioButton(self.gridFrame)
        self.tempRadioBtn.setMaximumSize(QtCore.QSize(107, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tempRadioBtn.setFont(font)
        self.tempRadioBtn.setObjectName(_fromUtf8("tempRadioBtn"))
        self.gridLayout_2.addWidget(self.tempRadioBtn, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.magnitudeRadioBtn = QtGui.QRadioButton(self.gridFrame)
        self.magnitudeRadioBtn.setObjectName(_fromUtf8("magnitudeRadioBtn"))
        self.verticalLayout_2.addWidget(self.magnitudeRadioBtn)
        self.phaseRadioBtn = QtGui.QRadioButton(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.phaseRadioBtn.setFont(font)
        self.phaseRadioBtn.setObjectName(_fromUtf8("phaseRadioBtn"))
        self.verticalLayout_2.addWidget(self.phaseRadioBtn)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 2, 1)
        self.graphicsViewTime = PlotWidget(self.tabTimescan)
        self.graphicsViewTime.setGeometry(QtCore.QRect(248, 8, 841, 681))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewTime.sizePolicy().hasHeightForWidth())
        self.graphicsViewTime.setSizePolicy(sizePolicy)
        self.graphicsViewTime.setMaximumSize(QtCore.QSize(1280, 1024))
        self.graphicsViewTime.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewTime.setLineWidth(5)
        self.graphicsViewTime.setObjectName(_fromUtf8("graphicsViewTime"))
        self.gridFrame_3 = QtGui.QFrame(self.tabTimescan)
        self.gridFrame_3.setGeometry(QtCore.QRect(5, 34, 241, 131))
        self.gridFrame_3.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_3.setObjectName(_fromUtf8("gridFrame_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridFrame_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.readTempControl = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readTempControl.setFont(font)
        self.readTempControl.setAutoFillBackground(True)
        self.readTempControl.setText(_fromUtf8(""))
        self.readTempControl.setObjectName(_fromUtf8("readTempControl"))
        self.gridLayout_4.addWidget(self.readTempControl, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.setTempControl = QtGui.QLineEdit(self.gridFrame_3)
        self.setTempControl.setObjectName(_fromUtf8("setTempControl"))
        self.gridLayout_4.addWidget(self.setTempControl, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.heaterOutBarControl = QtGui.QProgressBar(self.gridFrame_3)
        self.heaterOutBarControl.setProperty("value", 0)
        self.heaterOutBarControl.setOrientation(QtCore.Qt.Horizontal)
        self.heaterOutBarControl.setObjectName(_fromUtf8("heaterOutBarControl"))
        self.gridLayout_4.addWidget(self.heaterOutBarControl, 0, 1, 1, 1)
        self.gridFrame1 = QtGui.QFrame(self.tabTimescan)
        self.gridFrame1.setGeometry(QtCore.QRect(0, 210, 241, 101))
        self.gridFrame1.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame1.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame1.setObjectName(_fromUtf8("gridFrame1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridFrame1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.gridFrame1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.setFieldControl = QtGui.QLineEdit(self.gridFrame1)
        self.setFieldControl.setObjectName(_fromUtf8("setFieldControl"))
        self.gridLayout_3.addWidget(self.setFieldControl, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridFrame1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.readFieldControl = QtGui.QLabel(self.gridFrame1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readFieldControl.setFont(font)
        self.readFieldControl.setAutoFillBackground(True)
        self.readFieldControl.setText(_fromUtf8(""))
        self.readFieldControl.setObjectName(_fromUtf8("readFieldControl"))
        self.gridLayout_3.addWidget(self.readFieldControl, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabTimescan)
        self.label_2.setGeometry(QtCore.QRect(50, 9, 141, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tabTimescan)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 111, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridFrame_10 = QtGui.QFrame(self.tabTimescan)
        self.gridFrame_10.setGeometry(QtCore.QRect(4, 340, 241, 91))
        self.gridFrame_10.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_10.setObjectName(_fromUtf8("gridFrame_10"))
        self.gridLayout_15 = QtGui.QGridLayout(self.gridFrame_10)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.readMotPosControl = QtGui.QLabel(self.gridFrame_10)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readMotPosControl.setFont(font)
        self.readMotPosControl.setAutoFillBackground(True)
        self.readMotPosControl.setText(_fromUtf8(""))
        self.readMotPosControl.setObjectName(_fromUtf8("readMotPosControl"))
        self.gridLayout_15.addWidget(self.readMotPosControl, 1, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.gridFrame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_15.addWidget(self.label_40, 1, 0, 1, 1)
        self.setMotPosControl = QtGui.QLineEdit(self.gridFrame_10)
        self.setMotPosControl.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setMotPosControl.setObjectName(_fromUtf8("setMotPosControl"))
        self.gridLayout_15.addWidget(self.setMotPosControl, 0, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridFrame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_15.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.tabTimescan)
        self.label_44.setGeometry(QtCore.QRect(70, 319, 111, 20))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.tabMotionCtrlWidget.addTab(self.tabTimescan, _fromUtf8(""))
        self.tabHysteresis = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabHysteresis.sizePolicy().hasHeightForWidth())
        self.tabHysteresis.setSizePolicy(sizePolicy)
        self.tabHysteresis.setObjectName(_fromUtf8("tabHysteresis"))
        self.graphicsViewFieldSingle = PlotWidget(self.tabHysteresis)
        self.graphicsViewFieldSingle.setGeometry(QtCore.QRect(248, 1, 841, 350))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewFieldSingle.sizePolicy().hasHeightForWidth())
        self.graphicsViewFieldSingle.setSizePolicy(sizePolicy)
        self.graphicsViewFieldSingle.setMaximumSize(QtCore.QSize(911, 681))
        self.graphicsViewFieldSingle.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewFieldSingle.setObjectName(_fromUtf8("graphicsViewFieldSingle"))
        self.gridFrame_4 = QtGui.QFrame(self.tabHysteresis)
        self.gridFrame_4.setGeometry(QtCore.QRect(4, 70, 241, 191))
        self.gridFrame_4.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_4.setObjectName(_fromUtf8("gridFrame_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridFrame_4)
        self.gridLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.maxFieldMagn = QtGui.QLineEdit(self.gridFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        self.maxFieldMagn.setFont(font)
        self.maxFieldMagn.setAccessibleName(_fromUtf8(""))
        self.maxFieldMagn.setText(_fromUtf8(""))
        self.maxFieldMagn.setFrame(True)
        self.maxFieldMagn.setObjectName(_fromUtf8("maxFieldMagn"))
        self.horizontalLayout_6.addWidget(self.maxFieldMagn)
        self.stepFieldMagn = QtGui.QLineEdit(self.gridFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        self.stepFieldMagn.setFont(font)
        self.stepFieldMagn.setAccessibleName(_fromUtf8(""))
        self.stepFieldMagn.setText(_fromUtf8(""))
        self.stepFieldMagn.setFrame(True)
        self.stepFieldMagn.setObjectName(_fromUtf8("stepFieldMagn"))
        self.horizontalLayout_6.addWidget(self.stepFieldMagn)
        self.noHystCyclesMagn = QtGui.QLineEdit(self.gridFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        self.noHystCyclesMagn.setFont(font)
        self.noHystCyclesMagn.setObjectName(_fromUtf8("noHystCyclesMagn"))
        self.horizontalLayout_6.addWidget(self.noHystCyclesMagn)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 8, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.saveHystFileName = QtGui.QLineEdit(self.gridFrame_4)
        self.saveHystFileName.setObjectName(_fromUtf8("saveHystFileName"))
        self.horizontalLayout_8.addWidget(self.saveHystFileName)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.workDirMagn = QtGui.QPushButton(self.gridFrame_4)
        self.workDirMagn.setObjectName(_fromUtf8("workDirMagn"))
        self.gridLayout_7.addWidget(self.workDirMagn, 0, 0, 1, 2)
        self.startHyst = QtGui.QPushButton(self.gridFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startHyst.sizePolicy().hasHeightForWidth())
        self.startHyst.setSizePolicy(sizePolicy)
        self.startHyst.setObjectName(_fromUtf8("startHyst"))
        self.gridLayout_7.addWidget(self.startHyst, 9, 0, 1, 2)
        self.cancelHyst = QtGui.QPushButton(self.gridFrame_4)
        self.cancelHyst.setObjectName(_fromUtf8("cancelHyst"))
        self.gridLayout_7.addWidget(self.cancelHyst, 11, 0, 1, 2)
        self.graphicsViewFieldMulti = PlotWidget(self.tabHysteresis)
        self.graphicsViewFieldMulti.setGeometry(QtCore.QRect(247, 355, 841, 350))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewFieldMulti.sizePolicy().hasHeightForWidth())
        self.graphicsViewFieldMulti.setSizePolicy(sizePolicy)
        self.graphicsViewFieldMulti.setMaximumSize(QtCore.QSize(911, 681))
        self.graphicsViewFieldMulti.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewFieldMulti.setObjectName(_fromUtf8("graphicsViewFieldMulti"))
        self.gridFrame_6 = QtGui.QFrame(self.tabHysteresis)
        self.gridFrame_6.setGeometry(QtCore.QRect(2, 330, 241, 251))
        self.gridFrame_6.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_6.setObjectName(_fromUtf8("gridFrame_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridFrame_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.setDemagRamp = QtGui.QLineEdit(self.gridFrame_6)
        self.setDemagRamp.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setDemagRamp.setObjectName(_fromUtf8("setDemagRamp"))
        self.gridLayout_8.addWidget(self.setDemagRamp, 3, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_8.addWidget(self.label_26, 1, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.rotateYES = QtGui.QRadioButton(self.gridFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rotateYES.setFont(font)
        self.rotateYES.setObjectName(_fromUtf8("rotateYES"))
        self.gridLayout_6.addWidget(self.rotateYES, 0, 1, 1, 1)
        self.rotateNO = QtGui.QRadioButton(self.gridFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rotateNO.setFont(font)
        self.rotateNO.setObjectName(_fromUtf8("rotateNO"))
        self.gridLayout_6.addWidget(self.rotateNO, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 6, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_8.addWidget(self.label_28, 6, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_8.addWidget(self.label_25, 0, 0, 1, 1)
        self.setFieldMagn = QtGui.QLineEdit(self.gridFrame_6)
        self.setFieldMagn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setFieldMagn.setObjectName(_fromUtf8("setFieldMagn"))
        self.gridLayout_8.addWidget(self.setFieldMagn, 0, 1, 1, 1)
        self.readFieldMagn = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.readFieldMagn.setFont(font)
        self.readFieldMagn.setAutoFillBackground(True)
        self.readFieldMagn.setText(_fromUtf8(""))
        self.readFieldMagn.setObjectName(_fromUtf8("readFieldMagn"))
        self.gridLayout_8.addWidget(self.readFieldMagn, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 3, 0, 1, 1)
        self.demagFrequency = QtGui.QLineEdit(self.gridFrame_6)
        self.demagFrequency.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.demagFrequency.setObjectName(_fromUtf8("demagFrequency"))
        self.gridLayout_8.addWidget(self.demagFrequency, 4, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 5, 0, 1, 1)
        self.rotFrequency = QtGui.QLineEdit(self.gridFrame_6)
        self.rotFrequency.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rotFrequency.setObjectName(_fromUtf8("rotFrequency"))
        self.gridLayout_8.addWidget(self.rotFrequency, 5, 1, 1, 1)
        self.demagBtn = QtGui.QPushButton(self.tabHysteresis)
        self.demagBtn.setGeometry(QtCore.QRect(30, 600, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.demagBtn.setFont(font)
        self.demagBtn.setObjectName(_fromUtf8("demagBtn"))
        self.demagLabel = QtGui.QLabel(self.tabHysteresis)
        self.demagLabel.setGeometry(QtCore.QRect(30, 570, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.demagLabel.setFont(font)
        self.demagLabel.setText(_fromUtf8(""))
        self.demagLabel.setObjectName(_fromUtf8("demagLabel"))
        self.tabMotionCtrlWidget.addTab(self.tabHysteresis, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabMotionCtrlWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMotionCtrlWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MOKE CONTROL", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#0000ff;\">TEMPERATURE</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Output power", None))
        self.label_11.setText(_translate("MainWindow", "SetTemp (K)", None))
        self.setTempSetup.setPlaceholderText(_translate("MainWindow", "temperature", None))
        self.label_14.setText(_translate("MainWindow", "ReadTemp (K)", None))
        self.label_15.setText(_translate("MainWindow", "SetRamp(K/min.)", None))
        self.setTempRampSetup.setPlaceholderText(_translate("MainWindow", "temp. ramp", None))
        self.connectLakeshoreBtn.setText(_translate("MainWindow", "CONNECT LAKESHORE", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">FIELD</span></p></body></html>", None))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#008000;\">AZIMUTH</span></p></body></html>", None))
        self.label_41.setText(_translate("MainWindow", "ReadPosition", None))
        self.setMotPosSetup.setPlaceholderText(_translate("MainWindow", "set angle", None))
        self.label_46.setText(_translate("MainWindow", "SetVelocity (°/sec)", None))
        self.setMotVelocitySetup.setPlaceholderText(_translate("MainWindow", "set speed", None))
        self.label_48.setText(_translate("MainWindow", "Move (relative)", None))
        self.label_47.setText(_translate("MainWindow", "SetAcceleration", None))
        self.setMotAccSetup.setPlaceholderText(_translate("MainWindow", "set acc.", None))
        self.setMotDecSetup.setPlaceholderText(_translate("MainWindow", "set dec.", None))
        self.stopMotSetup.setText(_translate("MainWindow", "STOP", None))
        self.resetMotSetup.setText(_translate("MainWindow", "RESET", None))
        self.connectGMWBtn.setText(_translate("MainWindow", "CONNECT GMW", None))
        self.connectMotorBtn.setText(_translate("MainWindow", "CONNECT MOTOR", None))
        self.poleTypeGMWSetup.setStatusTip(_translate("MainWindow", "pole type", None))
        self.setFieldGMWSetup.setPlaceholderText(_translate("MainWindow", "field", None))
        self.gapValueGMWSetup.setStatusTip(_translate("MainWindow", "gap value", None))
        self.label_17.setText(_translate("MainWindow", "ReadField(mT)", None))
        self.label_18.setText(_translate("MainWindow", "SetField(mT)", None))
        self.label_19.setText(_translate("MainWindow", "Set Maximum", None))
        self.setMaxCurrentGMW.setPlaceholderText(_translate("MainWindow", "MAX current (Amp)", None))
        self.setFieldRampCAYLARSetup.setPlaceholderText(_translate("MainWindow", "field ramp", None))
        self.label_20.setText(_translate("MainWindow", "ReadField(mT)", None))
        self.setFieldCAYLARSetup.setPlaceholderText(_translate("MainWindow", "field", None))
        self.label_24.setText(_translate("MainWindow", "FieldRamp(mT)", None))
        self.label_21.setText(_translate("MainWindow", "SetField(mT)", None))
        self.gapValueCAYLARSetup.setStatusTip(_translate("MainWindow", "gap value", None))
        self.label_27.setText(_translate("MainWindow", "GapValue", None))
        self.connectCAYLARBtn.setText(_translate("MainWindow", "CONNECT CAYLAR", None))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#000000;\">DETECTION</span></p></body></html>", None))
        self.connectSRSBtn.setText(_translate("MainWindow", "CONNECT SRS lock-in", None))
        self.connectPrincetonBtn.setText(_translate("MainWindow", "CONNECT PRINCETON lock-in", None))
        self.autoMeasPrince.setText(_translate("MainWindow", "Auto Measure", None))
        self.autoOffsetPrince.setText(_translate("MainWindow", "Auto Offset", None))
        self.label_38.setText(_translate("MainWindow", "PHASE", None))
        self.label_36.setText(_translate("MainWindow", "MAGNITUDE", None))
        self.autoOffsetSRS.setText(_translate("MainWindow", "Auto Phase", None))
        self.autoMeasSRS.setText(_translate("MainWindow", "Auto Offset", None))
        self.resetSRS.setText(_translate("MainWindow", "RESET", None))
        self.autoSensSRS.setText(_translate("MainWindow", "Auto SENSITIVITY", None))
        self.label_35.setText(_translate("MainWindow", "MAGNITUDE", None))
        self.label_37.setText(_translate("MainWindow", "PHASE", None))
        self.tabMotionCtrlWidget.setTabText(self.tabMotionCtrlWidget.indexOf(self.tab), _translate("MainWindow", "SETUP", None))
        self.stopTimescan.setText(_translate("MainWindow", "STOP", None))
        self.startTimescan.setText(_translate("MainWindow", "START", None))
        self.saveTimescanFileName.setPlaceholderText(_translate("MainWindow", "timescan file name (+\'.txt\' !!!)", None))
        self.workDirControl.setText(_translate("MainWindow", "WorkDir", None))
        self.label_5.setText(_translate("MainWindow", "File Name", None))
        self.tempRadioBtn.setText(_translate("MainWindow", "temperature", None))
        self.magnitudeRadioBtn.setText(_translate("MainWindow", "magnitude", None))
        self.phaseRadioBtn.setText(_translate("MainWindow", "phase", None))
        self.label_4.setText(_translate("MainWindow", "Output power", None))
        self.label_8.setText(_translate("MainWindow", "SetTemp (K)", None))
        self.setTempControl.setPlaceholderText(_translate("MainWindow", "temperature", None))
        self.label_9.setText(_translate("MainWindow", "ReadTemp (K)", None))
        self.label_13.setText(_translate("MainWindow", "ReadField(mT)", None))
        self.setFieldControl.setPlaceholderText(_translate("MainWindow", "field", None))
        self.label_12.setText(_translate("MainWindow", "SetField(mT)", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">TEMPERATURE</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">FIELD</span></p></body></html>", None))
        self.label_40.setText(_translate("MainWindow", "ReadPosition", None))
        self.setMotPosControl.setPlaceholderText(_translate("MainWindow", "set angle", None))
        self.label_39.setText(_translate("MainWindow", "Move (relative)", None))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#008000;\">AZIMUTH</span></p></body></html>", None))
        self.tabMotionCtrlWidget.setTabText(self.tabMotionCtrlWidget.indexOf(self.tabTimescan), _translate("MainWindow", "CONTROL", None))
        self.maxFieldMagn.setPlaceholderText(_translate("MainWindow", "field", None))
        self.stepFieldMagn.setPlaceholderText(_translate("MainWindow", "step", None))
        self.noHystCyclesMagn.setPlaceholderText(_translate("MainWindow", "cycles", None))
        self.saveHystFileName.setPlaceholderText(_translate("MainWindow", "Hysteresis file name", None))
        self.workDirMagn.setText(_translate("MainWindow", "WorkDir", None))
        self.startHyst.setText(_translate("MainWindow", "START", None))
        self.cancelHyst.setText(_translate("MainWindow", "CANCEL", None))
        self.setDemagRamp.setPlaceholderText(_translate("MainWindow", "field rate(mT/step)", None))
        self.label_26.setText(_translate("MainWindow", "ReadField(mT)", None))
        self.rotateYES.setText(_translate("MainWindow", "Y", None))
        self.rotateNO.setText(_translate("MainWindow", "N", None))
        self.label_28.setText(_translate("MainWindow", "ROTATE?", None))
        self.label_25.setText(_translate("MainWindow", "SetField(mT)", None))
        self.setFieldMagn.setPlaceholderText(_translate("MainWindow", "field (mT)", None))
        self.label_22.setText(_translate("MainWindow", "Field Rate", None))
        self.demagFrequency.setPlaceholderText(_translate("MainWindow", "frequency (Hz)", None))
        self.label_29.setText(_translate("MainWindow", "Rotation Rate", None))
        self.rotFrequency.setPlaceholderText(_translate("MainWindow", "frequency (Hz)", None))
        self.demagBtn.setText(_translate("MainWindow", "DEMAG-it", None))
        self.tabMotionCtrlWidget.setTabText(self.tabMotionCtrlWidget.indexOf(self.tabHysteresis), _translate("MainWindow", "MAGNETIC MEASUREMENTS", None))

from pyqtgraph import PlotWidget
