# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SolMOKE_GUI.ui'
#
# Created: Tue Mar 15 08:11:24 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1122, 786)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1122, 786))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1122, 760))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabMotionCtrlWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMotionCtrlWidget.sizePolicy().hasHeightForWidth())
        self.tabMotionCtrlWidget.setSizePolicy(sizePolicy)
        self.tabMotionCtrlWidget.setMaximumSize(QtCore.QSize(1104, 742))
        self.tabMotionCtrlWidget.setObjectName(_fromUtf8("tabMotionCtrlWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(60, 10, 181, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridFrame_5 = QtGui.QFrame(self.tab)
        self.gridFrame_5.setGeometry(QtCore.QRect(10, 90, 291, 161))
        self.gridFrame_5.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_5.setObjectName(_fromUtf8("gridFrame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridFrame_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.readTempLabel_2 = QtGui.QLabel(self.gridFrame_5)
        self.readTempLabel_2.setAutoFillBackground(True)
        self.readTempLabel_2.setText(_fromUtf8(""))
        self.readTempLabel_2.setObjectName(_fromUtf8("readTempLabel_2"))
        self.gridLayout_5.addWidget(self.readTempLabel_2, 5, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.setTempLine_2 = QtGui.QLineEdit(self.gridFrame_5)
        self.setTempLine_2.setObjectName(_fromUtf8("setTempLine_2"))
        self.gridLayout_5.addWidget(self.setTempLine_2, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 5, 0, 1, 1)
        self.tempHeaterOutputBar_2 = QtGui.QProgressBar(self.gridFrame_5)
        self.tempHeaterOutputBar_2.setProperty("value", 0)
        self.tempHeaterOutputBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.tempHeaterOutputBar_2.setObjectName(_fromUtf8("tempHeaterOutputBar_2"))
        self.gridLayout_5.addWidget(self.tempHeaterOutputBar_2, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridFrame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)
        self.setTempRampLine_2 = QtGui.QLineEdit(self.gridFrame_5)
        self.setTempRampLine_2.setObjectName(_fromUtf8("setTempRampLine_2"))
        self.gridLayout_5.addWidget(self.setTempRampLine_2, 3, 1, 1, 1)
        self.connectLakeshoreBtn = QtGui.QPushButton(self.tab)
        self.connectLakeshoreBtn.setGeometry(QtCore.QRect(10, 50, 171, 31))
        self.connectLakeshoreBtn.setObjectName(_fromUtf8("connectLakeshoreBtn"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(470, 10, 131, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_45 = QtGui.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(830, 10, 131, 31))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.tabMotionCtrlWidget.addTab(self.tab, _fromUtf8(""))
        self.tabTimescan = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabTimescan.sizePolicy().hasHeightForWidth())
        self.tabTimescan.setSizePolicy(sizePolicy)
        self.tabTimescan.setMaximumSize(QtCore.QSize(1100, 705))
        self.tabTimescan.setMouseTracking(False)
        self.tabTimescan.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabTimescan.setAcceptDrops(False)
        self.tabTimescan.setAccessibleName(_fromUtf8(""))
        self.tabTimescan.setAccessibleDescription(_fromUtf8(""))
        self.tabTimescan.setAutoFillBackground(False)
        self.tabTimescan.setObjectName(_fromUtf8("tabTimescan"))
        self.gridFrame = QtGui.QFrame(self.tabTimescan)
        self.gridFrame.setGeometry(QtCore.QRect(4, 467, 241, 221))
        self.gridFrame.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.gridLayout = QtGui.QGridLayout(self.gridFrame)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stopTimescanBtn = QtGui.QPushButton(self.gridFrame)
        self.stopTimescanBtn.setObjectName(_fromUtf8("stopTimescanBtn"))
        self.gridLayout.addWidget(self.stopTimescanBtn, 7, 0, 1, 1)
        self.startTimescanBtn = QtGui.QPushButton(self.gridFrame)
        self.startTimescanBtn.setObjectName(_fromUtf8("startTimescanBtn"))
        self.gridLayout.addWidget(self.startTimescanBtn, 5, 0, 1, 1)
        self.saveTimescanFileName = QtGui.QLineEdit(self.gridFrame)
        self.saveTimescanFileName.setText(_fromUtf8(""))
        self.saveTimescanFileName.setObjectName(_fromUtf8("saveTimescanFileName"))
        self.gridLayout.addWidget(self.saveTimescanFileName, 2, 0, 1, 1)
        self.workDirBtn = QtGui.QPushButton(self.gridFrame)
        self.workDirBtn.setObjectName(_fromUtf8("workDirBtn"))
        self.gridLayout.addWidget(self.workDirBtn, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tempRadioBtn = QtGui.QRadioButton(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tempRadioBtn.setFont(font)
        self.tempRadioBtn.setObjectName(_fromUtf8("tempRadioBtn"))
        self.gridLayout_2.addWidget(self.tempRadioBtn, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lockInRadioBtn = QtGui.QRadioButton(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lockInRadioBtn.setFont(font)
        self.lockInRadioBtn.setObjectName(_fromUtf8("lockInRadioBtn"))
        self.gridLayout_2.addWidget(self.lockInRadioBtn, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 2, 1)
        self.graphicsViewTime = PlotWidget(self.tabTimescan)
        self.graphicsViewTime.setGeometry(QtCore.QRect(248, 8, 841, 681))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewTime.sizePolicy().hasHeightForWidth())
        self.graphicsViewTime.setSizePolicy(sizePolicy)
        self.graphicsViewTime.setMaximumSize(QtCore.QSize(1280, 1024))
        self.graphicsViewTime.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewTime.setLineWidth(5)
        self.graphicsViewTime.setObjectName(_fromUtf8("graphicsViewTime"))
        self.gridFrame_3 = QtGui.QFrame(self.tabTimescan)
        self.gridFrame_3.setGeometry(QtCore.QRect(5, 25, 241, 131))
        self.gridFrame_3.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_3.setObjectName(_fromUtf8("gridFrame_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridFrame_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.readTempLabel = QtGui.QLabel(self.gridFrame_3)
        self.readTempLabel.setAutoFillBackground(True)
        self.readTempLabel.setText(_fromUtf8(""))
        self.readTempLabel.setObjectName(_fromUtf8("readTempLabel"))
        self.gridLayout_4.addWidget(self.readTempLabel, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.setTempLine = QtGui.QLineEdit(self.gridFrame_3)
        self.setTempLine.setObjectName(_fromUtf8("setTempLine"))
        self.gridLayout_4.addWidget(self.setTempLine, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 5, 0, 1, 1)
        self.tempHeaterOutputBar = QtGui.QProgressBar(self.gridFrame_3)
        self.tempHeaterOutputBar.setProperty("value", 0)
        self.tempHeaterOutputBar.setOrientation(QtCore.Qt.Horizontal)
        self.tempHeaterOutputBar.setObjectName(_fromUtf8("tempHeaterOutputBar"))
        self.gridLayout_4.addWidget(self.tempHeaterOutputBar, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.setTempRampLine = QtGui.QLineEdit(self.gridFrame_3)
        self.setTempRampLine.setObjectName(_fromUtf8("setTempRampLine"))
        self.gridLayout_4.addWidget(self.setTempRampLine, 3, 1, 1, 1)
        self.gridFrame1 = QtGui.QFrame(self.tabTimescan)
        self.gridFrame1.setGeometry(QtCore.QRect(5, 178, 241, 111))
        self.gridFrame1.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame1.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame1.setObjectName(_fromUtf8("gridFrame1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridFrame1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.gridFrame1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.setFieldLine = QtGui.QLineEdit(self.gridFrame1)
        self.setFieldLine.setObjectName(_fromUtf8("setFieldLine"))
        self.gridLayout_3.addWidget(self.setFieldLine, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridFrame1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.readFieldLabel = QtGui.QLabel(self.gridFrame1)
        self.readFieldLabel.setAutoFillBackground(True)
        self.readFieldLabel.setText(_fromUtf8(""))
        self.readFieldLabel.setObjectName(_fromUtf8("readFieldLabel"))
        self.gridLayout_3.addWidget(self.readFieldLabel, 2, 1, 1, 1)
        self.poleTypeCB = QtGui.QComboBox(self.gridFrame1)
        self.poleTypeCB.setEditable(False)
        self.poleTypeCB.setObjectName(_fromUtf8("poleTypeCB"))
        self.gridLayout_3.addWidget(self.poleTypeCB, 0, 0, 1, 1)
        self.gapValueCB = QtGui.QComboBox(self.gridFrame1)
        self.gapValueCB.setObjectName(_fromUtf8("gapValueCB"))
        self.gridLayout_3.addWidget(self.gapValueCB, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabTimescan)
        self.label_2.setGeometry(QtCore.QRect(30, 4, 141, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tabTimescan)
        self.label_3.setGeometry(QtCore.QRect(43, 157, 111, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridFrame_10 = QtGui.QFrame(self.tabTimescan)
        self.gridFrame_10.setGeometry(QtCore.QRect(4, 315, 241, 141))
        self.gridFrame_10.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_10.setObjectName(_fromUtf8("gridFrame_10"))
        self.gridLayout_15 = QtGui.QGridLayout(self.gridFrame_10)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.readPositionLabel = QtGui.QLabel(self.gridFrame_10)
        self.readPositionLabel.setAutoFillBackground(True)
        self.readPositionLabel.setText(_fromUtf8(""))
        self.readPositionLabel.setObjectName(_fromUtf8("readPositionLabel"))
        self.gridLayout_15.addWidget(self.readPositionLabel, 3, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.gridFrame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_15.addWidget(self.label_40, 3, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.gridFrame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_15.addWidget(self.label_42, 1, 0, 1, 1)
        self.setRotPositionLine = QtGui.QLineEdit(self.gridFrame_10)
        self.setRotPositionLine.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setRotPositionLine.setObjectName(_fromUtf8("setRotPositionLine"))
        self.gridLayout_15.addWidget(self.setRotPositionLine, 0, 1, 1, 1)
        self.setRotAccLine = QtGui.QLineEdit(self.gridFrame_10)
        self.setRotAccLine.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setRotAccLine.setObjectName(_fromUtf8("setRotAccLine"))
        self.gridLayout_15.addWidget(self.setRotAccLine, 2, 1, 1, 1)
        self.setRotVelocityLine = QtGui.QLineEdit(self.gridFrame_10)
        self.setRotVelocityLine.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setRotVelocityLine.setObjectName(_fromUtf8("setRotVelocityLine"))
        self.gridLayout_15.addWidget(self.setRotVelocityLine, 1, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.gridFrame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_15.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridFrame_10)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_15.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.tabTimescan)
        self.label_44.setGeometry(QtCore.QRect(70, 294, 111, 20))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.tabMotionCtrlWidget.addTab(self.tabTimescan, _fromUtf8(""))
        self.tabHysteresis = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabHysteresis.sizePolicy().hasHeightForWidth())
        self.tabHysteresis.setSizePolicy(sizePolicy)
        self.tabHysteresis.setObjectName(_fromUtf8("tabHysteresis"))
        self.graphicsViewFieldSingle = PlotWidget(self.tabHysteresis)
        self.graphicsViewFieldSingle.setGeometry(QtCore.QRect(248, 1, 841, 350))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewFieldSingle.sizePolicy().hasHeightForWidth())
        self.graphicsViewFieldSingle.setSizePolicy(sizePolicy)
        self.graphicsViewFieldSingle.setMaximumSize(QtCore.QSize(911, 681))
        self.graphicsViewFieldSingle.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewFieldSingle.setObjectName(_fromUtf8("graphicsViewFieldSingle"))
        self.gridFrame_4 = QtGui.QFrame(self.tabHysteresis)
        self.gridFrame_4.setGeometry(QtCore.QRect(4, 70, 241, 191))
        self.gridFrame_4.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_4.setObjectName(_fromUtf8("gridFrame_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridFrame_4)
        self.gridLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.maxFieldLine = QtGui.QLineEdit(self.gridFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        self.maxFieldLine.setFont(font)
        self.maxFieldLine.setAccessibleName(_fromUtf8(""))
        self.maxFieldLine.setText(_fromUtf8(""))
        self.maxFieldLine.setFrame(True)
        self.maxFieldLine.setObjectName(_fromUtf8("maxFieldLine"))
        self.horizontalLayout_6.addWidget(self.maxFieldLine)
        self.stepFieldLine = QtGui.QLineEdit(self.gridFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        self.stepFieldLine.setFont(font)
        self.stepFieldLine.setAccessibleName(_fromUtf8(""))
        self.stepFieldLine.setText(_fromUtf8(""))
        self.stepFieldLine.setFrame(True)
        self.stepFieldLine.setObjectName(_fromUtf8("stepFieldLine"))
        self.horizontalLayout_6.addWidget(self.stepFieldLine)
        self.noHystCycles = QtGui.QLineEdit(self.gridFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        self.noHystCycles.setFont(font)
        self.noHystCycles.setObjectName(_fromUtf8("noHystCycles"))
        self.horizontalLayout_6.addWidget(self.noHystCycles)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 8, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.saveHystFileName = QtGui.QLineEdit(self.gridFrame_4)
        self.saveHystFileName.setObjectName(_fromUtf8("saveHystFileName"))
        self.horizontalLayout_8.addWidget(self.saveHystFileName)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.workDirBtn_1 = QtGui.QPushButton(self.gridFrame_4)
        self.workDirBtn_1.setObjectName(_fromUtf8("workDirBtn_1"))
        self.gridLayout_7.addWidget(self.workDirBtn_1, 0, 0, 1, 2)
        self.startHystBtn = QtGui.QPushButton(self.gridFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startHystBtn.sizePolicy().hasHeightForWidth())
        self.startHystBtn.setSizePolicy(sizePolicy)
        self.startHystBtn.setObjectName(_fromUtf8("startHystBtn"))
        self.gridLayout_7.addWidget(self.startHystBtn, 9, 0, 1, 2)
        self.cancelHystBtn = QtGui.QPushButton(self.gridFrame_4)
        self.cancelHystBtn.setObjectName(_fromUtf8("cancelHystBtn"))
        self.gridLayout_7.addWidget(self.cancelHystBtn, 11, 0, 1, 2)
        self.graphicsViewFieldSingleMulti = PlotWidget(self.tabHysteresis)
        self.graphicsViewFieldSingleMulti.setGeometry(QtCore.QRect(247, 355, 841, 350))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewFieldSingleMulti.sizePolicy().hasHeightForWidth())
        self.graphicsViewFieldSingleMulti.setSizePolicy(sizePolicy)
        self.graphicsViewFieldSingleMulti.setMaximumSize(QtCore.QSize(911, 681))
        self.graphicsViewFieldSingleMulti.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewFieldSingleMulti.setObjectName(_fromUtf8("graphicsViewFieldSingleMulti"))
        self.gridFrame_6 = QtGui.QFrame(self.tabHysteresis)
        self.gridFrame_6.setGeometry(QtCore.QRect(2, 360, 241, 191))
        self.gridFrame_6.setFrameShape(QtGui.QFrame.Panel)
        self.gridFrame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridFrame_6.setObjectName(_fromUtf8("gridFrame_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridFrame_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_23 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 0, 0, 1, 1)
        self.currOutputBar = QtGui.QProgressBar(self.gridFrame_6)
        self.currOutputBar.setAcceptDrops(False)
        self.currOutputBar.setMinimum(-200)
        self.currOutputBar.setMaximum(200)
        self.currOutputBar.setProperty("value", 0)
        self.currOutputBar.setTextVisible(True)
        self.currOutputBar.setOrientation(QtCore.Qt.Horizontal)
        self.currOutputBar.setObjectName(_fromUtf8("currOutputBar"))
        self.gridLayout_8.addWidget(self.currOutputBar, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 4, 0, 1, 1)
        self.setDemagStepsLine = QtGui.QLineEdit(self.gridFrame_6)
        self.setDemagStepsLine.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setDemagStepsLine.setObjectName(_fromUtf8("setDemagStepsLine"))
        self.gridLayout_8.addWidget(self.setDemagStepsLine, 4, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_8.addWidget(self.label_26, 2, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.rotateYESradioBtn = QtGui.QRadioButton(self.gridFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rotateYESradioBtn.setFont(font)
        self.rotateYESradioBtn.setObjectName(_fromUtf8("rotateYESradioBtn"))
        self.gridLayout_6.addWidget(self.rotateYESradioBtn, 0, 1, 1, 1)
        self.rotateNOradioBtn = QtGui.QRadioButton(self.gridFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rotateNOradioBtn.setFont(font)
        self.rotateNOradioBtn.setObjectName(_fromUtf8("rotateNOradioBtn"))
        self.gridLayout_6.addWidget(self.rotateNOradioBtn, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 5, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_8.addWidget(self.label_28, 5, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridFrame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_8.addWidget(self.label_25, 1, 0, 1, 1)
        self.setFieldLine_2 = QtGui.QLineEdit(self.gridFrame_6)
        self.setFieldLine_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setFieldLine_2.setObjectName(_fromUtf8("setFieldLine_2"))
        self.gridLayout_8.addWidget(self.setFieldLine_2, 1, 1, 1, 1)
        self.readFieldLabel_2 = QtGui.QLabel(self.gridFrame_6)
        self.readFieldLabel_2.setAutoFillBackground(True)
        self.readFieldLabel_2.setText(_fromUtf8(""))
        self.readFieldLabel_2.setObjectName(_fromUtf8("readFieldLabel_2"))
        self.gridLayout_8.addWidget(self.readFieldLabel_2, 2, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.tabHysteresis)
        self.label_27.setGeometry(QtCore.QRect(40, 340, 111, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.demagBtn = QtGui.QPushButton(self.tabHysteresis)
        self.demagBtn.setGeometry(QtCore.QRect(30, 560, 191, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Optima"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.demagBtn.setFont(font)
        self.demagBtn.setObjectName(_fromUtf8("demagBtn"))
        self.tabMotionCtrlWidget.addTab(self.tabHysteresis, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabMotionCtrlWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMotionCtrlWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MOKE CONTROL", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#0000ff;\">TEMPERATURE</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Output power", None))
        self.label_11.setText(_translate("MainWindow", "SetTemp (K)", None))
        self.setTempLine_2.setPlaceholderText(_translate("MainWindow", "temperature", None))
        self.label_14.setText(_translate("MainWindow", "ReadTemp (K)", None))
        self.label_15.setText(_translate("MainWindow", "SetRamp(K/min.)", None))
        self.setTempRampLine_2.setPlaceholderText(_translate("MainWindow", "temp. ramp", None))
        self.connectLakeshoreBtn.setText(_translate("MainWindow", "CONNECT LAKESHORE", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">FIELD</span></p></body></html>", None))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#008000;\">AZIMUTH</span></p></body></html>", None))
        self.tabMotionCtrlWidget.setTabText(self.tabMotionCtrlWidget.indexOf(self.tab), _translate("MainWindow", "GENERAL SETUP", None))
        self.stopTimescanBtn.setText(_translate("MainWindow", "STOP", None))
        self.startTimescanBtn.setText(_translate("MainWindow", "START", None))
        self.saveTimescanFileName.setPlaceholderText(_translate("MainWindow", "timescan file name", None))
        self.workDirBtn.setText(_translate("MainWindow", "WorkDir", None))
        self.label_5.setText(_translate("MainWindow", "File Name", None))
        self.tempRadioBtn.setText(_translate("MainWindow", "temp", None))
        self.label.setText(_translate("MainWindow", "Sensor", None))
        self.lockInRadioBtn.setText(_translate("MainWindow", "lockIn", None))
        self.label_4.setText(_translate("MainWindow", "Output power", None))
        self.label_8.setText(_translate("MainWindow", "SetTemp (K)", None))
        self.setTempLine.setPlaceholderText(_translate("MainWindow", "temperature", None))
        self.label_9.setText(_translate("MainWindow", "ReadTemp (K)", None))
        self.label_10.setText(_translate("MainWindow", "SetRamp(K/min.)", None))
        self.setTempRampLine.setPlaceholderText(_translate("MainWindow", "temp. ramp", None))
        self.label_13.setText(_translate("MainWindow", "ReadField(mT)", None))
        self.setFieldLine.setPlaceholderText(_translate("MainWindow", "field", None))
        self.label_12.setText(_translate("MainWindow", "SetField(mT)", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">TEMPERATURE</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">FIELD</span></p></body></html>", None))
        self.label_40.setText(_translate("MainWindow", "ReadPosition", None))
        self.label_42.setText(_translate("MainWindow", "SetVelocity (°/sec)", None))
        self.setRotPositionLine.setPlaceholderText(_translate("MainWindow", "set angle", None))
        self.setRotAccLine.setPlaceholderText(_translate("MainWindow", "set acc.", None))
        self.setRotVelocityLine.setPlaceholderText(_translate("MainWindow", "set speed", None))
        self.label_43.setText(_translate("MainWindow", "SetAcceleration", None))
        self.label_39.setText(_translate("MainWindow", "Move (relative)", None))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#008000;\">AZIMUTH</span></p></body></html>", None))
        self.tabMotionCtrlWidget.setTabText(self.tabMotionCtrlWidget.indexOf(self.tabTimescan), _translate("MainWindow", "GENERAL CONTROL", None))
        self.maxFieldLine.setPlaceholderText(_translate("MainWindow", "field", None))
        self.stepFieldLine.setPlaceholderText(_translate("MainWindow", "step", None))
        self.noHystCycles.setPlaceholderText(_translate("MainWindow", "cycles", None))
        self.saveHystFileName.setPlaceholderText(_translate("MainWindow", "Hysteresis file name", None))
        self.workDirBtn_1.setText(_translate("MainWindow", "WorkDir", None))
        self.startHystBtn.setText(_translate("MainWindow", "START", None))
        self.cancelHystBtn.setText(_translate("MainWindow", "CANCEL", None))
        self.label_23.setText(_translate("MainWindow", "Coil current(A)", None))
        self.currOutputBar.setFormat(_translate("MainWindow", "%p%", None))
        self.label_22.setText(_translate("MainWindow", "STEPS", None))
        self.setDemagStepsLine.setPlaceholderText(_translate("MainWindow", "field steps", None))
        self.label_26.setText(_translate("MainWindow", "ReadField(T)", None))
        self.rotateYESradioBtn.setText(_translate("MainWindow", "Y", None))
        self.rotateNOradioBtn.setText(_translate("MainWindow", "N", None))
        self.label_28.setText(_translate("MainWindow", "ROTATE?", None))
        self.label_25.setText(_translate("MainWindow", "SetField(T)", None))
        self.setFieldLine_2.setPlaceholderText(_translate("MainWindow", "field", None))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">FIELD</span></p></body></html>", None))
        self.demagBtn.setText(_translate("MainWindow", "DEMAG-it", None))
        self.tabMotionCtrlWidget.setTabText(self.tabMotionCtrlWidget.indexOf(self.tabHysteresis), _translate("MainWindow", "MAGNETIC MEASUREMENTS", None))

from pyqtgraph import PlotWidget
